networks:
  backend:
    name: backend

services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - PGUSER=${POSTGRES_USER}
    volumes:
        - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
        - backend
    command: postgres -c 'max_connections=500'
    restart: always

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 8008:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui

  registry:
    image: registry:2
    container_name: registry_02
    volumes:
        - ${REGISTRY_DATA_PATH}:/var/lib/registry
    ports:
        - 127.0.0.1:5000:5000
    restart: always
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true

