all:
  children:
    observer:
      hosts:
        Prometheus:
          ansible_connection: local
    target:
      hosts:
        Prometheus:
          ansible_host: 192.168.1.103

        Production:
          ansible_host: 10.0.1.*
